# -*- coding: utf-8 -*-
"""
Created on Fri Aug 23 01:40:05 2024

@author: Samsung
"""

#config.toml
[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"